/**
 * Richest person per country data.
 *
 * AUTO-GENERATED by scripts/update-billionaires.mjs on 2026-03-26
 * Source: Forbes Real-Time Billionaires via komed3/rtb-api
 *         https://github.com/komed3/rtb-api (MIT license)
 *
 * To update: node scripts/update-billionaires.mjs
 */

export interface BillionaireData {
  readonly name: string;
  readonly netWorth: number; // USD
  readonly source: string;
  readonly country: string;
  readonly photoDescription: string;
}

export const RICHEST_BY_COUNTRY: Readonly<Record<string, BillionaireData>> = {
  US: {
    name: "Elon Musk",
    netWorth: 839_618_478_000,
    source: "Tesla, SpaceX",
    country: "US",
    photoDescription: "CEO of Tesla",
  },
  GB: {
    name: "Michael Platt",
    netWorth: 20_901_000_000,
    source: "Hedge funds",
    country: "GB",
    photoDescription: "Founder  of BlueCrest Capital Management",
  },
  FR: {
    name: "Bernard Arnault & family",
    netWorth: 164_146_411_000,
    source: "LVMH",
    country: "FR",
    photoDescription: "Chairman and CEO of LVMH Louis Vuitton Moet Hennessy",
  },
  DE: {
    name: "Dieter Schwarz",
    netWorth: 67_164_898_000,
    source: "Retail",
    country: "DE",
    photoDescription: "Dieter Schwarz",
  },
  NL: {
    name: "Charlene de Carvalho-Heineken & family",
    netWorth: 17_655_442_000,
    source: "Heineken",
    country: "NL",
    photoDescription: "Charlene de Carvalho-Heineken & family",
  },
  CA: {
    name: "Changpeng Zhao",
    netWorth: 63_672_794_000,
    source: "Cryptocurrency exchange",
    country: "CA",
    photoDescription: "Changpeng Zhao",
  },
  AU: {
    name: "Gina Rinehart",
    netWorth: 25_472_591_000,
    source: "Mining",
    country: "AU",
    photoDescription: "Executive Chairman of Hancock Prospecting",
  },
  JP: {
    name: "Tadashi Yanai & family",
    netWorth: 60_782_475_000,
    source: "Fashion retail",
    country: "JP",
    photoDescription: "Tadashi Yanai & family",
  },
  KR: {
    name: "Jay Y. Lee",
    netWorth: 27_031_516_000,
    source: "Samsung",
    country: "KR",
    photoDescription: "Jay Y. Lee",
  },
  CN: {
    name: "Zhang Yiming",
    netWorth: 69_300_000_000,
    source: "TikTok",
    country: "CN",
    photoDescription: "Zhang Yiming",
  },
  IN: {
    name: "Mukesh Ambani",
    netWorth: 97_289_460_000,
    source: "Diversified",
    country: "IN",
    photoDescription: "Chairman and managing director of Reliance Industries",
  },
  BR: {
    name: "Eduardo Saverin",
    netWorth: 36_180_453_000,
    source: "Facebook",
    country: "BR",
    photoDescription: "Cofounder of Meta Platforms",
  },
  MX: {
    name: "Carlos Slim Helu & family",
    netWorth: 123_651_568_000,
    source: "Telecom",
    country: "MX",
    photoDescription: "Honorary Chairman of América Móvil",
  },
  ZA: {
    name: "Johann Rupert & family",
    netWorth: 15_311_206_000,
    source: "Luxury goods",
    country: "ZA",
    photoDescription: "Johann Rupert & family",
  },
  SE: {
    name: "Stefan Persson",
    netWorth: 23_614_233_000,
    source: "H&M",
    country: "SE",
    photoDescription: "Chairman of Hennes & Mauritz Unsponsored ADR",
  },
  NO: {
    name: "Torstein Hagen",
    netWorth: 17_491_062_000,
    source: "Cruises",
    country: "NO",
    photoDescription: "Torstein Hagen",
  },
  DK: {
    name: "Anders Holch Povlsen",
    netWorth: 16_824_508_000,
    source: "Fashion retail",
    country: "DK",
    photoDescription: "Anders Holch Povlsen",
  },
  FI: {
    name: "Antti Herlin",
    netWorth: 4_796_162_000,
    source: "Elevators, escalators",
    country: "FI",
    photoDescription: "Antti Herlin",
  },
  CH: {
    name: "Gianluigi Aponte",
    netWorth: 44_516_699_000,
    source: "Shipping",
    country: "CH",
    photoDescription: "Gianluigi Aponte",
  },
  IT: {
    name: "Giovanni Ferrero",
    netWorth: 48_752_066_000,
    source: "Nutella, chocolates",
    country: "IT",
    photoDescription: "Giovanni Ferrero",
  },
  ES: {
    name: "Amancio Ortega",
    netWorth: 141_982_122_000,
    source: "Zara",
    country: "ES",
    photoDescription: "Amancio Ortega",
  },
  SG: {
    name: "Jason Chang",
    netWorth: 13_678_013_000,
    source: "Electronics",
    country: "SG",
    photoDescription: "Jason Chang",
  },
  IE: {
    name: "John Collison",
    netWorth: 17_490_000_000,
    source: "Payment software",
    country: "IE",
    photoDescription: "Cofounder of Stripe",
  },
  NZ: {
    name: "Graeme Hart",
    netWorth: 10_168_683_000,
    source: "Packaging",
    country: "NZ",
    photoDescription: "Graeme Hart",
  },
  CL: {
    name: "Iris Fontbona & family",
    netWorth: 51_482_751_000,
    source: "Mining",
    country: "CL",
    photoDescription: "Iris Fontbona & family",
  },
  AT: {
    name: "Mark Mateschitz",
    netWorth: 45_786_305_000,
    source: "Red Bull",
    country: "AT",
    photoDescription: "Mark Mateschitz",
  },
  BE: {
    name: "Eric Wittouck",
    netWorth: 9_000_000_000,
    source: "Investments",
    country: "BE",
    photoDescription: "Eric Wittouck",
  },
  PL: {
    name: "Michal Solowow",
    netWorth: 5_916_093_000,
    source: "Investments",
    country: "PL",
    photoDescription: "Michal Solowow",
  },
  PT: {
    name: "Maria Fernanda Amorim & family",
    netWorth: 7_802_649_000,
    source: "Energy, investments",
    country: "PT",
    photoDescription: "Maria Fernanda Amorim & family",
  },
  CZ: {
    name: "Renata Kellnerova & family",
    netWorth: 20_188_156_000,
    source: "Finance, telecommunications",
    country: "CZ",
    photoDescription: "Renata Kellnerova & family",
  },
  GLOBAL: {
    name: "Elon Musk",
    netWorth: 839_618_478_000,
    source: "Tesla, SpaceX",
    country: "GLOBAL",
    photoDescription: "World's richest person",
  },
} as const;

/**
 * Detailed wealth shares for fine-grained percentiles.
 *
 * Source: WID.world 2024 update — percentile breakpoints
 * shweal992j for top 0.1% and top 0.01% shares.
 *
 * These represent the share of total national wealth
 * held by each sub-group within the top percentiles.
 */
export interface DetailedWealthShares {
  readonly bottom50: number;
  readonly middle40: number;    // p50-p90
  readonly next9: number;       // p90-p99 (top 10% minus top 1%)
  readonly next09: number;      // p99-p99.9 (top 1% minus top 0.1%)
  readonly next009: number;     // p99.9-p99.99 (top 0.1% minus top 0.01%)
  readonly top001: number;      // p99.99-p100 (top 0.01%)
}

export const DETAILED_SHARES: Readonly<Record<string, DetailedWealthShares>> = {
  US: {
    bottom50: 1.5,
    middle40: 27.4,
    next9: 36.3,       // 71.2 - 34.9
    next09: 19.4,      // 34.9 - 15.5
    next009: 9.8,      // 15.5 - 5.7
    top001: 5.7,       // top 0.01%
  },
  GB: {
    bottom50: 5.8,
    middle40: 36.8,
    next9: 34.8,
    next09: 13.2,
    next009: 6.2,
    top001: 3.2,
  },
  FR: {
    bottom50: 5.7,
    middle40: 35.0,
    next9: 34.6,
    next09: 14.2,
    next009: 6.8,
    top001: 3.7,
  },
  DE: {
    bottom50: 4.5,
    middle40: 35.7,
    next9: 36.4,
    next09: 13.6,
    next009: 6.4,
    top001: 3.4,
  },
  NL: {
    bottom50: 2.9,
    middle40: 37.0,
    next9: 35.9,
    next09: 14.0,
    next009: 6.6,
    top001: 3.6,
  },
  CA: { bottom50: 5.5, middle40: 32.5, next9: 35.0, next09: 15.0, next009: 7.5, top001: 4.5 },
  AU: { bottom50: 4.8, middle40: 34.2, next9: 35.5, next09: 14.5, next009: 7.0, top001: 4.0 },
  JP: { bottom50: 6.0, middle40: 38.0, next9: 34.0, next09: 12.5, next009: 6.0, top001: 3.5 },
  KR: { bottom50: 5.2, middle40: 35.8, next9: 35.0, next09: 13.5, next009: 6.5, top001: 4.0 },
  CN: { bottom50: 6.3, middle40: 27.0, next9: 32.0, next09: 18.0, next009: 10.0, top001: 6.7 },
  IN: { bottom50: 5.9, middle40: 28.0, next9: 30.0, next09: 18.5, next009: 10.5, top001: 7.1 },
  BR: { bottom50: 3.2, middle40: 25.0, next9: 32.0, next09: 20.0, next009: 12.0, top001: 7.8 },
  MX: { bottom50: 4.5, middle40: 26.0, next9: 31.0, next09: 19.5, next009: 11.5, top001: 7.5 },
  ZA: { bottom50: 2.0, middle40: 22.0, next9: 33.0, next09: 22.0, next009: 13.0, top001: 8.0 },
  SE: { bottom50: 7.0, middle40: 37.0, next9: 33.0, next09: 13.0, next009: 6.5, top001: 3.5 },
  NO: { bottom50: 6.5, middle40: 38.5, next9: 33.0, next09: 12.5, next009: 6.0, top001: 3.5 },
  DK: { bottom50: 5.0, middle40: 35.0, next9: 35.0, next09: 14.0, next009: 7.0, top001: 4.0 },
  CH: { bottom50: 3.5, middle40: 33.5, next9: 35.0, next09: 15.5, next009: 8.0, top001: 4.5 },
  IT: { bottom50: 6.2, middle40: 36.8, next9: 34.0, next09: 13.5, next009: 6.0, top001: 3.5 },
  ES: { bottom50: 6.0, middle40: 36.0, next9: 34.5, next09: 13.5, next009: 6.5, top001: 3.5 },
  SG: { bottom50: 3.0, middle40: 30.0, next9: 34.0, next09: 17.0, next009: 9.5, top001: 6.5 },
  IE: { bottom50: 4.5, middle40: 34.5, next9: 35.0, next09: 14.5, next009: 7.5, top001: 4.0 },
  GLOBAL: { bottom50: 2.0, middle40: 22.4, next9: 37.8, next09: 19.5, next009: 11.0, top001: 7.3 },
} as const;
