/**
 * Economic indicators over time — wages, consumer prices, and house prices.
 *
 * AUTO-GENERATED by scripts/update-economic-data.mjs on 2026-03-26
 *
 * All series are indexed to a common base year (2000 = 100) so they can be
 * compared on the same chart. The gap between lines reveals how wages, prices,
 * and housing costs have diverged.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * SOURCES (all publicly downloadable):
 *
 * Wages — OECD Average Annual Wages (AV_AN_WAGE)
 *   Measure: USD, constant prices, constant PPP
 *   Dataset: OECD.ELS.SAE, DSD_EARNINGS@AV_AN_WAGE
 *   URL: https://data-explorer.oecd.org → Average Annual Wages
 *
 * Consumer Prices — World Bank, Consumer Price Index (FP.CPI.TOTL)
 *   Measure: Index (2010 = 100), rebased to 2000 = 100
 *   URL: https://data.worldbank.org/indicator/FP.CPI.TOTL
 *
 * House Prices — BIS Residential Property Prices via FRED
 *   Measure: Real (CPI-deflated), index (2010 = 100), rebased to 2000 = 100
 *   Series: QUSR628BIS (US), QGBR628BIS (UK), QFRR628BIS (FR),
 *           QDER628BIS (DE), QNLR628BIS (NL)
 *   URL: https://data.bis.org/topics/RPP
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * HOW THE INDEX IS COMPUTED:
 *   index = (value / value_2000) × 100
 *
 * Raw source values used to compute each index:
//   DE:  1995=80.48  2000=85.70  2005=92.46  2010=100.00  2015=107.20  2020=113.02  2023=131.89
//   FR:  1995=79.47  2000=84.39  2005=92.76  2010=100.00  2015=105.58  2020=110.57  2023=124.03
//   GB:  1995=73.93  2000=81.47  2005=88.12  2010=100.00  2015=110.96  2020=120.81  2023=142.74
//   NL:  1995=73.83  2000=81.95  2005=92.68  2010=100.00  2015=109.18  2020=117.38  2023=137.67
//   US:  1995=69.88  2000=78.97  2005=89.56  2010=100.00  2015=108.70  2020=118.69  2023=139.74
//
//   FR:  1995=47889.15  2000=50645.17  2005=54272.51  2010=57867.38  2015=59600.31  2020=58590.77  2023=60140.54
//   DE:  1995=57123.15  2000=59354.42  2005=60548.73  2010=61167.67  2015=66389.95  2020=69750.81  2023=68104.23
//   NL:  1995=71342.97  2000=72084.87  2005=75061.28  2010=79440.63  2015=80218.00  2020=80227.28  2023=74549.09
//   GB:  1995=45386.18  2000=52593.34  2005=59357.29  2010=61224.21  2015=61166.96  2020=62432.98  2023=62797.05
//   US:  1995=56536.40  2000=64927.98  2005=67961.01  2010=71439.50  2015=74825.13  2020=82783.41  2023=82078.43
 */

export interface EconomicDataPoint {
  readonly year: number;
  /** Real average wages, indexed 2000 = 100 (OECD, constant USD PPP) */
  readonly wageIndex: number;
  /** Consumer Price Index, indexed 2000 = 100 (World Bank) */
  readonly cpiIndex: number;
  /** Real house prices, indexed 2000 = 100 (BIS via FRED) */
  readonly housePriceIndex: number;
}

export interface CountryEconomicData {
  readonly countryCode: string;
  readonly series: readonly EconomicDataPoint[];
}

const US_SERIES: readonly EconomicDataPoint[] = [
  { year: 1995, wageIndex: 87.1, cpiIndex: 88.5, housePriceIndex: 86.6 },
  { year: 2000, wageIndex: 100, cpiIndex: 100, housePriceIndex: 100 },
  { year: 2005, wageIndex: 104.7, cpiIndex: 113.4, housePriceIndex: 148.9 },
  { year: 2010, wageIndex: 110, cpiIndex: 126.6, housePriceIndex: 106.7 },
  { year: 2015, wageIndex: 115.2, cpiIndex: 137.6, housePriceIndex: 119.8 },
  { year: 2020, wageIndex: 127.5, cpiIndex: 150.3, housePriceIndex: 140.5 },
  { year: 2023, wageIndex: 126.4, cpiIndex: 176.9, housePriceIndex: 164.8 },
] as const;

const GB_SERIES: readonly EconomicDataPoint[] = [
  { year: 1995, wageIndex: 86.3, cpiIndex: 90.7, housePriceIndex: 71.3 },
  { year: 2000, wageIndex: 100, cpiIndex: 100, housePriceIndex: 100 },
  { year: 2005, wageIndex: 112.9, cpiIndex: 108.2, housePriceIndex: 163.9 },
  { year: 2010, wageIndex: 116.4, cpiIndex: 122.7, housePriceIndex: 159.4 },
  { year: 2015, wageIndex: 116.3, cpiIndex: 136.2, housePriceIndex: 160.9 },
  { year: 2020, wageIndex: 118.7, cpiIndex: 148.3, housePriceIndex: 179.1 },
  { year: 2023, wageIndex: 119.4, cpiIndex: 175.2, housePriceIndex: 184.3 },
] as const;

const FR_SERIES: readonly EconomicDataPoint[] = [
  { year: 1995, wageIndex: 94.6, cpiIndex: 94.2, housePriceIndex: 91.5 },
  { year: 2000, wageIndex: 100, cpiIndex: 100, housePriceIndex: 100 },
  { year: 2005, wageIndex: 107.2, cpiIndex: 109.9, housePriceIndex: 152.5 },
  { year: 2010, wageIndex: 114.3, cpiIndex: 118.5, housePriceIndex: 171 },
  { year: 2015, wageIndex: 117.7, cpiIndex: 125.1, housePriceIndex: 166.2 },
  { year: 2020, wageIndex: 115.7, cpiIndex: 131, housePriceIndex: 181.2 },
  { year: 2023, wageIndex: 118.7, cpiIndex: 147, housePriceIndex: 190.2 },
] as const;

const DE_SERIES: readonly EconomicDataPoint[] = [
  { year: 1995, wageIndex: 96.2, cpiIndex: 93.9, housePriceIndex: 110.1 },
  { year: 2000, wageIndex: 100, cpiIndex: 100, housePriceIndex: 100 },
  { year: 2005, wageIndex: 102, cpiIndex: 107.9, housePriceIndex: 89.3 },
  { year: 2010, wageIndex: 103.1, cpiIndex: 116.7, housePriceIndex: 83.5 },
  { year: 2015, wageIndex: 111.9, cpiIndex: 125.1, housePriceIndex: 90.7 },
  { year: 2020, wageIndex: 117.5, cpiIndex: 131.9, housePriceIndex: 116.3 },
  { year: 2023, wageIndex: 114.7, cpiIndex: 153.9, housePriceIndex: 116 },
] as const;

const NL_SERIES: readonly EconomicDataPoint[] = [
  { year: 1995, wageIndex: 99, cpiIndex: 90.1, housePriceIndex: 61.6 },
  { year: 2000, wageIndex: 100, cpiIndex: 100, housePriceIndex: 100 },
  { year: 2005, wageIndex: 104.1, cpiIndex: 113.1, housePriceIndex: 121.3 },
  { year: 2010, wageIndex: 110.2, cpiIndex: 122, housePriceIndex: 120.1 },
  { year: 2015, wageIndex: 111.3, cpiIndex: 133.2, housePriceIndex: 97.1 },
  { year: 2020, wageIndex: 111.3, cpiIndex: 143.2, housePriceIndex: 127.8 },
  { year: 2023, wageIndex: 103.4, cpiIndex: 168, housePriceIndex: 144.1 },
] as const;

export const PURCHASING_POWER: Readonly<Record<string, CountryEconomicData>> = {
  US: { countryCode: "US", series: US_SERIES },
  GB: { countryCode: "GB", series: GB_SERIES },
  FR: { countryCode: "FR", series: FR_SERIES },
  DE: { countryCode: "DE", series: DE_SERIES },
  NL: { countryCode: "NL", series: NL_SERIES },
} as const;

export const ECONOMIC_SOURCES = {
  wages: {
    name: "OECD Average Annual Wages",
    dataset: "DSD_EARNINGS@AV_AN_WAGE",
    measure: "USD, constant prices, constant PPP",
    url: "https://data-explorer.oecd.org",
  },
  cpi: {
    name: "World Bank Consumer Price Index",
    dataset: "FP.CPI.TOTL",
    measure: "Index (2010 = 100), rebased to 2000 = 100",
    url: "https://data.worldbank.org/indicator/FP.CPI.TOTL",
  },
  housePrices: {
    name: "BIS Residential Property Prices",
    dataset: "Selected Residential Property Prices (real, CPI-deflated)",
    measure: "Index (2010 = 100), rebased to 2000 = 100",
    url: "https://data.bis.org/topics/RPP",
  },
} as const;
